In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
#Load Dataset and clean , short and filter dataset
df = pd.read_csv("dataset.csv")
df.shape


#split Product_Name column
parts = df["Product Name"].str.split(r"\s+", n=2, expand=True)

df["Product_Name"] = parts[0] + " " + parts[1].fillna("")
df["Description"] = parts[2]

df["Product_Name"] = df["Product_Name"].str.strip()

#Remove OFF and replace NaN with 0
df["Discount"] = df["Discount"].str.replace("OFF", "", regex=False).str.strip()
df["Discount"] = df["Discount"].str.replace("%", "", regex=False)
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce").fillna(0).astype(int)
df["Discount"] = df["Discount"].fillna("0")

#Price Column Clean
df["Prices"] = df["Prices"].str.replace(r"[^\d.]", "", regex=True)
df["Prices"] = pd.to_numeric(df["Prices"], errors="coerce")

In [9]:
# Arrange Columns in Sequence

df = df[[
    "Product Name",
    "Product_Name",
    "Description",
    "Prices",
    "Discount",
    "Category",
    "Date",
    "Source"
]]

In [10]:
#Price Analysis
print("Average Price:", df["Prices"].mean()) #Check avg price
print("Minimum Price:", df["Prices"].min())  #Check min Price
print("Maximum Price:", df["Prices"].max())  #check Max price
print("Median Price:", df["Prices"].median()) # check median

Average Price: 62987.75347484838
Minimum Price: 195.0
Maximum Price: 1889990.0
Median Price: 37999.0

In [11]:
#Category Analysis
df["Category"].value_counts() # Count products in each category
df.groupby("Category")["Prices"].mean().round(2) # Avg price Category
df.groupby("Category")["Prices"].mean().idxmax() #Highest avg price by category

'TV'

In [12]:
#Discount Analysis

df["Discount"].mean().round(2)  # Average discount
df["Discount"].max()  # Maximum discount
df["Discount"].min()  # Minimum discount
df.groupby("Category")["Discount"].mean().round(2)  # Average discount by category
df.groupby("Category")["Discount"].mean().idxmax()  # Category with highest average discount
df.groupby("Category")["Discount"].max()  # Maximum discount by category

Category
Laptop          81
Mobile          60
Refrigerator    66
TV              71
Tablets         62
Watches         95
Name: Discount, dtype: int64

In [122]:
# Product Analysis
df.loc[df["Prices"].idxmax()]  # Most expensive product
df.loc[df["Prices"].idxmin()]  # Cheapest product
df.nlargest(5, "Prices")  # Top 5 expensive products
df.nsmallest(5, "Prices")  # Top 5 cheapest products

,Product Name,Prices,Discount,Category,Date,Source,Product_Name,Description
2435,Sleeve Carry Case for JioBook with Front Pocke...,195.0,77,Laptop,2023-09-08,Reliance Digital,Sleeve Carry,"Case for JioBook with Front Pocket, Blue, 33.7..."
2536,"Zebronics Lite Laptop Stand, Silver A75-NS2000",279.0,81,Laptop,2023-09-08,Reliance Digital,Zebronics Lite,"Laptop Stand, Silver A75-NS2000"
2321,"Zebronics Laptop Stand, Black, A218-NS1000",399.0,71,Laptop,2023-09-08,Reliance Digital,Zebronics Laptop,"Stand, Black, A218-NS1000"
2773,Lapcare LROADSA2098 Laptop Power Adapter with ...,599.0,0,Laptop,2023-09-08,Reliance Digital,Lapcare LROADSA2098,Laptop Power Adapter with Over Current Protect...
2787,Lapcare LOADHY5023 Laptop Adapter Designed for...,599.0,0,Laptop,2023-09-08,Reliance Digital,Lapcare LOADHY5023,Laptop Adapter Designed for HP 65 Watt with 4....

In [13]:
# Product Name Analysis

df["Product_Name"].nunique()  # Total unique products
df["Product_Name"].value_counts().head(10)  # Top 10 frequently appearing products
df["Product_Name"].isnull().sum()  # Missing product names
df["Product_Name"].duplicated().sum()  # Duplicate product names

np.int64(2091)

In [141]:
# Price Distribution Analysis

df["Prices"].describe()  # Price distribution summary
df["Prices"].value_counts().head(10)  # Top 10 most frequently occurring prices
df["Prices"].skew().round(2)  # Price distribution skewness
df["Prices"].quantile([0.25, 0.50, 0.75])  # Price quartiles

0.25    16994.0
0.50    37999.0
0.75    80997.0
Name: Prices, dtype: float64

In [14]:
# Relationship Analysis

df[["Prices", "Discount"]].corr().round(2)  # Correlation between price and discount
df.groupby("Category")[["Prices", "Discount"]].mean().round(2)  # Average price and discount by category
df.nlargest(5, "Discount")  # Top 5 products with highest discount
df.nlargest(5, "Prices")[["Product Name", "Prices", "Discount", "Category"]]  # Expensive products with discount

,Product Name,Prices,Discount,Category
1419,"LG 245 cm (97 inches), OLED evo AI TV (G6) wit...",1889990.0,18,TV
1428,"LG 210 cm (83 inches), OLED evo AI TV (G6) wit...",699990.0,0,TV
1418,"Samsung 216 cm (85 inches), Micro RGB 4K Samsu...",669990.0,20,TV
1467,TCL 215.9 cm (85 inches) SQD Mini LED Google T...,599990.0,0,TV
1425,"LG 210 cm (83 inches), OLED evo TV (C6) with a...",580600.0,23,TV

In [15]:
# Q1. Which product category has the highest average price?
df.groupby("Category")["Prices"].mean().idxmax()


# Q2. Which product category offers the highest average discount?
df.groupby("Category")["Discount"].mean().idxmax()


# Q3. Which are the top 5 most expensive products?
df.nlargest(5, "Prices")[["Product Name", "Prices", "Category"]]


# Q4. Is there any relationship between product prices and discounts?
df[["Prices", "Discount"]].corr()


# Q5. Which product category contains the highest number of products?
df["Category"].value_counts().idxmax()


# Q6. Are there any unusual or invalid product prices and discount values?
df[(df["Prices"] <= 0) | (df["Discount"] < 0) | (df["Discount"] > 100)]


# Q7. Which products have the highest discounts?
df.nlargest(5, "Discount")[["Product Name", "Discount", "Prices", "Category"]]

,Product Name,Discount,Prices,Category
1819,"Fire-Boltt ASSAULT Smart Watch, 3.81 cm (1.5 i...",95,899.0,Watches
1862,Fire-Boltt Ninja Phantom Smart Watch 46.4 mm (...,95,999.0,Watches
1875,Fire-Boltt Ninja Phantom Smart Watch 46.4 mm (...,95,999.0,Watches
1891,FireBoltt Ninja Call Pro Plus Smart Watch with...,94,1199.0,Watches
1927,"FireBoltt Ninja Call Pro Plus Smart Watch, 4.6...",94,1199.0,Watches

In [17]:
# Check relationship between Price and Discount

df["Prices"].corr(df["Discount"])

np.float64(-0.1580738629571075)

### Hypothesis Testing — Conclusion

I checked the relationship between product prices and discounts. The correlation value was **-0.158**, which indicates a weak negative relationship between them.

This means there is very little linear relationship between product prices and discounts in my dataset.

In [21]:
# Detect Potential Data Issues

df.isnull().sum()  # Check missing values
df.duplicated().sum()  # Check duplicate rows
df[df["Prices"] <= 0]  # Check invalid prices
df[(df["Discount"] < 0) | (df["Discount"] > 100)]  # Check invalid discounts

Empty DataFrame
Columns: [Product Name, Product_Name, Description, Prices, Discount, Category, Date, Source]
Index: []

### Data Issues — Conclusion

I checked the dataset for missing values, duplicate rows, invalid prices, and invalid discount values. These checks helped me identify potential data quality issues.